catalog: "resources/str_catalogs/catalog_strchive.cleaned.thap11_zfhx3.json"

pathvars:
  samples_dir: "samples/UMKL"
  # samples_dir: "samples/KUL_FAM000017"
  results: "thap11_zfhx3"
  annotsv_dir: "resources/AnnotSV"
  phenosv_dir: "resources/PhenoSV"
  caddsv_dir: "resources/CADDSV"
