# Path to JSON file which is compatible with `stranger`.
catalog: "resources/str_catalogs/catalog_strchive.cleaned.json"

# Path to folder with samples.
# Within this folder, there should be a folder for each sample.
# In each sample's folder, there should be a file like `<sample>.repeats.vcf.gz`
# as well as the corresponding index file ending in `.tbi`.
samples_dir: "samples/KUL_FAM000017"

# Path to the master key containing sample and family IDs, phenotypes, etc.
master_key: "samples/UMKLM_KUL_master_key_n4530.tsv"
